---
version: "3.8"

volumes:
  data:

services:
  weewx:
    build:
      args:
        - VERSION=4.5.1
      context: .
      dockerfile: Dockerfile
    image: ioprev/weewx:4.5.1
    network_mode: host
    container_name: weewx
    init: true
    restart: "no"
    # devices:
    #   - "/dev/ttyUSB0:/dev/ttyUSB0"
    #user: 1001:1001
    volumes:
      - type: bind
        source: /var/weewx
        target: /data
      - type: bind
        source: /dev/log
        target: /dev/log
    environment:
      - TIMEZONE=US/Eastern
      - WEEWX_UID=weewx
      - WEEWX_GID=weewx
